import { LetterRepository } from '@/usecase/letter/letter.repository'
import { Letter } from '@/usecase/letter/letter.types'

const mockReceivedLetters: Letter[] = [
  {
    id: 'letter-r1',
    message: '素敵な文章ですね。読んでいて心が温かくなりました。',
    senderName: 'はなこ',
    senderAvatar: null,
    senderHandle: 'hanako_writes',
    articleId: '1',
    articleTitle: '春の日記',
    stampEmoji: '🌸',
    hearted: true,
    createdAt: new Date('2026-03-15'),
  },
  {
    id: 'letter-r2',
    message: '共感しました。私も同じことを考えていたので、言葉にしてくれて嬉しいです。',
    senderName: '田中太郎',
    senderAvatar: null,
    senderHandle: 'tanaka_t',
    articleId: '3',
    articleTitle: '散歩道にて',
    stampEmoji: '✨',
    hearted: false,
    createdAt: new Date('2026-03-10'),
  },
  {
    id: 'letter-r3',
    message: 'この本、私も読みました！感想が似ていて驚きました。',
    senderName: 'まりこ',
    senderAvatar: null,
    senderHandle: 'mariko_book',
    articleId: '7',
    articleTitle: '読書記録',
    stampEmoji: '📚',
    hearted: false,
    createdAt: new Date('2026-02-28'),
  },
  {
    id: 'letter-r4',
    message: 'いつも楽しく読んでいます。更新を楽しみにしています。',
    senderName: 'ゆうき',
    senderAvatar: null,
    senderHandle: 'yuki_daily',
    articleId: '2',
    articleTitle: '日記',
    stampEmoji: '☕',
    hearted: true,
    createdAt: new Date('2026-02-20'),
  },
  {
    id: 'letter-r5',
    message: '雨の日の描写がとても美しくて、情景が目に浮かびました。',
    senderName: 'あおい',
    senderAvatar: null,
    senderHandle: 'aoi_sky',
    articleId: '10',
    articleTitle: '雨の日',
    stampEmoji: '🌧️',
    hearted: false,
    createdAt: new Date('2026-02-10'),
  },
]

const mockSentLetters: Letter[] = [
  {
    id: 'letter-s1',
    message: '旅の記録、楽しく拝読しました。写真も素敵ですね。',
    senderName: 'saigo_don',
    senderAvatar: null,
    senderHandle: 'saigo_don',
    articleId: 'ext-1',
    articleTitle: '北海道ひとり旅',
    stampEmoji: '🗾',
    hearted: false,
    createdAt: new Date('2026-03-12'),
  },
  {
    id: 'letter-s2',
    message: 'レシピ参考になりました。今度作ってみます！',
    senderName: 'saigo_don',
    senderAvatar: null,
    senderHandle: 'saigo_don',
    articleId: 'ext-2',
    articleTitle: '簡単パスタの作り方',
    stampEmoji: '🍝',
    hearted: false,
    createdAt: new Date('2026-02-25'),
  },
  {
    id: 'letter-s3',
    message: '静かな文体がとても好きです。また書いてください。',
    senderName: 'saigo_don',
    senderAvatar: null,
    senderHandle: 'saigo_don',
    articleId: 'ext-3',
    articleTitle: '窓辺の風景',
    stampEmoji: '🪟',
    hearted: false,
    createdAt: new Date('2026-01-30'),
  },
]

export const letterMockRepo: LetterRepository = {
  findReceived: async () => mockReceivedLetters,
  findSent: async () => mockSentLetters,
}
